create table if not exists public.calendar_calendars (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  slug text,
  color text not null default '#3B82F6',
  timezone text not null default 'UTC',
  is_default boolean not null default false,
  is_visible boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, slug)
);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  calendar_id bigint not null references public.calendar_calendars (id) on delete cascade,
  uid uuid not null default gen_random_uuid() unique,
  reference text not null,
  title text not null,
  description text,
  location text,
  meeting_url text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  all_day boolean not null default false,
  timezone text not null default 'UTC',
  status text not null default 'confirmed'
    check (status in ('tentative', 'confirmed', 'cancelled')),
  show_as text not null default 'busy'
    check (show_as in ('free', 'busy', 'tentative', 'out_of_office')),
  source text not null default 'manual'
    check (source in (
      'manual', 'booking', 'import', 'api',
      'calendly', 'google', 'outlook', 'zoom', 'hubspot', 'acuity', 'custom_webhook'
    )),
  contact_id bigint references public.contacts (id) on delete set null,
  color text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_events_valid_range check (ends_at > starts_at),
  unique (user_id, reference)
);

create table if not exists public.calendar_event_attendees (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.calendar_events (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  contact_id bigint references public.contacts (id) on delete set null,
  email text,
  display_name text,
  is_organizer boolean not null default false,
  response_status text not null default 'needs_action'
    check (response_status in (
      'needs_action', 'accepted', 'declined', 'tentative'
    )),
  created_at timestamptz not null default now(),
  constraint calendar_event_attendee_identity check (
    user_id is not null or contact_id is not null or email is not null
  )
);

create index if not exists calendar_calendars_user_id_idx
  on public.calendar_calendars (user_id);

create index if not exists calendar_events_user_id_starts_idx
  on public.calendar_events (user_id, starts_at);

create index if not exists calendar_events_calendar_id_starts_idx
  on public.calendar_events (calendar_id, starts_at);

create index if not exists calendar_events_range_idx
  on public.calendar_events (starts_at, ends_at);

create index if not exists calendar_event_attendees_event_id_idx
  on public.calendar_event_attendees (event_id);

alter table public.calendar_calendars enable row level security;
alter table public.calendar_events enable row level security;
alter table public.calendar_event_attendees enable row level security;

drop policy if exists "calendar_calendars_authenticated_all" on public.calendar_calendars;
create policy "calendar_calendars_authenticated_all"
on public.calendar_calendars for all to authenticated using (true) with check (true);

drop policy if exists "calendar_events_authenticated_all" on public.calendar_events;
create policy "calendar_events_authenticated_all"
on public.calendar_events for all to authenticated using (true) with check (true);

drop policy if exists "calendar_event_attendees_authenticated_all" on public.calendar_event_attendees;
create policy "calendar_event_attendees_authenticated_all"
on public.calendar_event_attendees for all to authenticated using (true) with check (true);
