create table if not exists public.calendar_availability_rules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  calendar_id bigint not null references public.calendar_calendars (id) on delete cascade,

  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  effective_from date,
  effective_until date,

  created_at timestamptz not null default now(),

  constraint calendar_availability_rules_valid_range check (end_time > start_time)
);

create index if not exists calendar_availability_rules_user_id_idx
  on public.calendar_availability_rules (user_id);

create index if not exists calendar_availability_rules_calendar_id_idx
  on public.calendar_availability_rules (calendar_id);

alter table public.calendar_availability_rules enable row level security;

drop policy if exists "calendar_availability_rules_authenticated_all" on public.calendar_availability_rules;
create policy "calendar_availability_rules_authenticated_all"
on public.calendar_availability_rules
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

